<div class="form-group text-left">
    <label for="country">{!! trans('site.country') !!}.</label>

        <select class="form-control"
                name="country" id="country">
            <option value="">{!! trans('site.select_country') !!}</option>
            <option value="Afghanistan">{!! trans('countries.Afghanistan') !!}</option>
            <option value="Albania">{!! trans('countries.Albania') !!}</option>
            <option value="Algeria">{!! trans('countries.Algeria') !!}</option>
            <option value="American Samoa">{!! trans('countries.American Samoa') !!}</option>
            <option value="Andorra">{!! trans('countries.Andorra') !!}</option>
            <option value="Angola">{!! trans('countries.Angola') !!}</option>
            <option value="Anguilla">{!! trans('countries.Anguilla') !!}</option>
            <option value="Antarctica">{!! trans('countries.Antarctica') !!}</option>
            <option value="Antigua and Barbuda">{!! trans('countries.Antigua and Barbuda') !!}</option>
            <option value="Argentina">{!! trans('countries.Argentina') !!}</option>
            <option value="Armenia">{!! trans('countries.Armenia') !!}</option>
            <option value="Aruba">{!! trans('countries.Aruba') !!}</option>
            <option value="Australia">{!! trans('countries.Australia') !!}</option>
            <option value="Austria">{!! trans('countries.Austria') !!}</option>
            <option value="Azerbaijan">{!! trans('countries.Azerbaijan') !!}</option>
            <option value="Bahamas">{!! trans('countries.Bahamas') !!}</option>
            <option value="Bahrain">{!! trans('countries.Bahrain') !!}</option>
            <option value="Bangladesh">{!! trans('countries.Bangladesh') !!}</option>
            <option value="Barbados">{!! trans('countries.Barbados') !!}</option>
            <option value="Belarus">{!! trans('countries.Belarus') !!}</option>
            <option value="Belgium">{!! trans('countries.Belgium') !!}</option>
            <option value="Belize">{!! trans('countries.Belize') !!}</option>
            <option value="Benin">{!! trans('countries.Benin') !!}</option>
            <option value="Bermuda">{!! trans('countries.Bermuda') !!}</option>
            <option value="Bhutan">{!! trans('countries.Bhutan') !!}</option>
            <option value="Bolivia">{!! trans('countries.Bolivia') !!}</option>
            <option value="Bonaire, Sint Eustatius and Saba">{!! trans('countries.Bonaire, Sint Eustatius and Saba') !!}</option>
            <option value="Bosnia and Herzegovina">{!! trans('countries.Bosnia and Herzegovina') !!}</option>
            <option value="Botswana">{!! trans('countries.Botswana') !!}</option>
            <option value="Bouvet Island">{!! trans('countries.Bouvet Island') !!}</option>
            <option value="Brazil">{!! trans('countries.Brazil') !!}</option>
            <option value="British Indian Ocean Territory">{!! trans('countries.British Indian Ocean Territory') !!}</option>
            <option value="Brunei Darussalam">{!! trans('countries.Brunei Darussalam') !!}</option>
            <option value="Bulgaria">{!! trans('countries.Bulgaria') !!}</option>
            <option value="Burkina Faso">{!! trans('countries.Burkina Faso') !!}</option>
            <option value="Burundi">{!! trans('countries.Burundi') !!}</option>
            <option value="Cambodia">{!! trans('countries.Cambodia') !!}</option>
            <option value="Cameroon">{!! trans('countries.Cameroon') !!}</option>
            <option value="Canada">{!! trans('countries.Canada') !!}</option>
            <option value="Cape Verde">{!! trans('countries.Cape Verde') !!}</option>
            <option value="Cayman Islands">{!! trans('countries.Cayman Islands') !!}</option>
            <option value="Central African Republic">{!! trans('countries.Central African Republic') !!}</option>
            <option value="Chad">{!! trans('countries.Chad') !!}</option>
            <option value="Chile">{!! trans('countries.Chile') !!}</option>
            <option value="China">{!! trans('countries.China') !!}</option>
            <option value="Christmas Island">{!! trans('countries.Christmas Island') !!}</option>
            <option value="Cocos (Keeling) Islands">{!! trans('countries.Cocos (Keeling) Islands') !!}</option>
            <option value="Colombia">{!! trans('countries.Colombia') !!}</option>
            <option value="Comoros">{!! trans('countries.Comoros') !!}</option>
            <option value="Congo">{!! trans('countries.Congo') !!}</option>
            <option value="Congo, Democratic Republic of the Congo">{!! trans('countries.Congo, Democratic Republic of the Congo') !!}</option>
            <option value="Cook Islands">{!! trans('countries.Cook Islands') !!}</option>
            <option value="Costa Rica">{!! trans('countries.Costa Rica') !!}</option>
            <option value="Cote DIvoire">{!! trans('countries.Cote DIvoire') !!}</option>
            <option value="Croatia">{!! trans('countries.Croatia') !!}</option>
            <option value="Cuba">{!! trans('countries.Cuba') !!}</option>
            <option value="Curacao">{!! trans('countries.Curacao') !!}</option>
            <option value="Cyprus">{!! trans('countries.Cyprus') !!}</option>
            <option value="Czech Republic">{!! trans('countries.Czech Republic') !!}</option>
            <option value="Denmark">{!! trans('countries.Denmark') !!}</option>
            <option value="Djibouti">{!! trans('countries.Djibouti') !!}</option>
            <option value="Dominica">{!! trans('countries.Dominica') !!}</option>
            <option value="Dominican Republic">{!! trans('countries.Dominican Republic') !!}</option>
            <option value="Ecuador">{!! trans('countries.Ecuador') !!}</option>
            <option value="Egypt">{!! trans('countries.Egypt') !!}</option>
            <option value="El Salvador">{!! trans('countries.El Salvador') !!}</option>
            <option value="Equatorial Guinea">{!! trans('countries.Equatorial Guinea') !!}</option>
            <option value="Eritrea">{!! trans('countries.Eritrea') !!}</option>
            <option value="Estonia">{!! trans('countries.Estonia') !!}</option>
            <option value="Ethiopia">{!! trans('countries.Ethiopia') !!}</option>
            <option value="Falkland Islands(Malvinas)">{!! trans('countries.Falkland Islands(Malvinas)') !!}</option>
            <option value="Faroe Islands">{!! trans('countries.Faroe Islands') !!}</option>
            <option value="Fiji">{!! trans('countries.Fiji') !!}</option>
            <option value="Finland">{!! trans('countries.Finland') !!}</option>
            <option value="France">{!! trans('countries.France') !!}</option>
            <option value="French Guiana">{!! trans('countries.French Guiana') !!}</option>
            <option value="French Polynesia">{!! trans('countries.French Polynesia') !!}</option>
            <option value="French Southern Territories">{!! trans('countries.French Southern Territories') !!}</option>
            <option value="Gabon">{!! trans('countries.Gabon') !!}</option>
            <option value="Gambia">{!! trans('countries.Gambia') !!}</option>
            <option value="Georgia">{!! trans('countries.Georgia') !!}</option>
            <option value="Germany">{!! trans('countries.Germany') !!}</option>
            <option value="Ghana">{!! trans('countries.Ghana') !!}</option>
            <option value="Gibraltar">{!! trans('countries.Gibraltar') !!}</option>
            <option value="Greece">{!! trans('countries.Greece') !!}</option>
            <option value="Greenland">{!! trans('countries.Greenland') !!}</option>
            <option value="Grenada">{!! trans('countries.Grenada') !!}</option>
            <option value="Guadeloupe">{!! trans('countries.Guadeloupe') !!}</option>
            <option value="Guam">{!! trans('countries.Guam') !!}</option>
            <option value="Guatemala">{!! trans('countries.Guatemala') !!}</option>
            <option value="Guernsey">{!! trans('countries.Guernsey') !!}</option>
            <option value="Guinea">{!! trans('countries.Guinea') !!}</option>
            <option value="Guinea-Bissau">{!! trans('countries.Guinea-Bissau') !!}</option>
            <option value="Guyana">{!! trans('countries.Guyana') !!}</option>
            <option value="Haiti">{!! trans('countries.Haiti') !!}</option>
            <option value="Heard Island and McDonald Islands">{!! trans('countries.Heard Island and McDonald Islands') !!}</option>
            <option value="Holy See(Vatican City State)">{!! trans('countries.Holy See(Vatican City State)') !!}</option>
            <option value="Honduras">{!! trans('countries.Honduras') !!}</option>
            <option value="Hong Kong">{!! trans('countries.Hong Kong') !!}</option>
            <option value="Hungary">{!! trans('countries.Hungary') !!}</option>
            <option value="Iceland">{!! trans('countries.Iceland') !!}</option>
            <option value="India">{!! trans('countries.India') !!}</option>
            <option value="Indonesia">{!! trans('countries.Indonesia') !!}</option>
            <option value="Iran, Islamic Republic of">{!! trans('countries.Iran, Islamic Republic of') !!}</option>
            <option value="Iraq">{!! trans('countries.Iraq') !!}</option>
            <option value="Ireland">{!! trans('countries.Ireland') !!}</option>
            <option value="Isle of Man">{!! trans('countries.Isle of Man') !!}</option>
            <option value="Israel">{!! trans('countries.Israel') !!}</option>
            <option value="Italy">{!! trans('countries.Italy') !!}</option>
            <option value="Jamaica">{!! trans('countries.Jamaica') !!}</option>
            <option value="Japan">{!! trans('countries.Japan') !!}</option>
            <option value="Jersey">{!! trans('countries.Jersey') !!}</option>
            <option value="Jordan">{!! trans('countries.Jordan') !!}</option>
            <option value="Kazakhstan">{!! trans('countries.Kazakhstan') !!}</option>
            <option value="Kenya">{!! trans('countries.Kenya') !!}</option>
            <option value="Kiribati">{!! trans('countries.Kiribati') !!}</option>
            <option value="Korea,Democratic Peoples Republic of">{!! trans('countries.Korea,Democratic Peoples Republic of') !!}</option>
            <option value="Korea, Republic of">{!! trans('countries.Korea, Republic of') !!}</option>
            <option value="Kosovo">{!! trans('countries.Kosovo') !!}</option>
            <option value="Kuwait">{!! trans('countries.Kuwait') !!}</option>
            <option value="Kyrgyzstan">{!! trans('countries.Kyrgyzstan') !!}</option>
            <option value="Lao Peoples Democratic Republic">{!! trans('countries.Lao Peoples Democratic Republic') !!}</option>
            <option value="Latvia">{!! trans('countries.Latvia') !!}</option>
            <option value="Lebanon">{!! trans('countries.Lebanon') !!}</option>
            <option value="Lesotho">{!! trans('countries.Lesotho') !!}</option>
            <option value="Liberia">{!! trans('countries.Liberia') !!}</option>
            <option value="Libyan Arab Jamahiriya">{!! trans('countries.Libyan Arab Jamahiriya') !!}</option>
            <option value="Liechtenstein">{!! trans('countries.Liechtenstein') !!}</option>
            <option value="Lithuania">{!! trans('countries.Lithuania') !!}</option>
            <option value="Luxembourg">{!! trans('countries.Luxembourg') !!}</option>
            <option value="Macao">{!! trans('countries.Macao') !!}</option>
            <option value="Macedonia, the Former Yugoslav Republic of">{!! trans('countries.Macedonia, the Former Yugoslav Republic of') !!}</option>
            <option value="Madagascar">{!! trans('countries.Madagascar') !!}</option>
            <option value="Malawi">{!! trans('countries.Malawi') !!}</option>
            <option value="Malaysia">{!! trans('countries.Malaysia') !!}</option>
            <option value="Maldives">{!! trans('countries.Maldives') !!}</option>
            <option value="Mali">{!! trans('countries.Mali') !!}</option>
            <option value="Malta">{!! trans('countries.Malta') !!}</option>
            <option value="Marshall Islands">{!! trans('countries.Marshall Islands') !!}</option>
            <option value="Martinique">{!! trans('countries.Martinique') !!}</option>
            <option value="Mauritania">{!! trans('countries.Mauritania') !!}</option>
            <option value="Mauritius">{!! trans('countries.Mauritius') !!}</option>
            <option value="Mayotte">{!! trans('countries.Mayotte') !!}</option>
            <option value="Mexico">{!! trans('countries.Mexico') !!}</option>
            <option value="Micronesia, Federated States of">{!! trans('countries.Micronesia, Federated States of') !!}</option>
            <option value="Moldova, Republic of">{!! trans('countries.Moldova, Republic of') !!}</option>
            <option value="Monaco">{!! trans('countries.Monaco') !!}</option>
            <option value="Mongolia">{!! trans('countries.Mongolia') !!}</option>
            <option value="Montenegro">{!! trans('countries.Montenegro') !!}</option>
            <option value="Montserrat">{!! trans('countries.Montserrat') !!}</option>
            <option value="Morocco">{!! trans('countries.Morocco') !!}</option>
            <option value="Mozambique">{!! trans('countries.Mozambique') !!}</option>
            <option value="Myanmar">{!! trans('countries.Myanmar') !!}</option>
            <option value="Namibia">{!! trans('countries.Namibia') !!}</option>
            <option value="Nauru">{!! trans('countries.Nauru') !!}</option>
            <option value="Nepal">{!! trans('countries.Nepal') !!}</option>
            <option value="Netherlands">{!! trans('countries.Netherlands') !!}</option>
            <option value="Netherlands Antilles">{!! trans('countries.Netherlands Antilles') !!}</option>
            <option value="New Caledonia">{!! trans('countries.New Caledonia') !!}</option>
            <option value="New Zealand">{!! trans('countries.New Zealand') !!}</option>
            <option value="Nicaragua">{!! trans('countries.Nicaragua') !!}</option>
            <option value="Niger">{!! trans('countries.Niger') !!}</option>
            <option value="Nigeria">{!! trans('countries.Nigeria') !!}</option>
            <option value="Niue">{!! trans('countries.Niue') !!}</option>
            <option value="Norfolk Island">{!! trans('countries.Norfolk Island') !!}</option>
            <option value="Northern Mariana Islands">{!! trans('countries.Northern Mariana Islands') !!}</option>
            <option value="Norway">{!! trans('countries.Norway') !!}</option>
            <option value="Oman">{!! trans('countries.Oman') !!}</option>
            <option value="Pakistan">{!! trans('countries.Pakistan') !!}</option>
            <option value="Palau">{!! trans('countries.Palau') !!}</option>
            <option value="Palestinian Territory, Occupied">{!! trans('countries.Palestinian Territory, Occupied') !!}</option>
            <option value="Panama">{!! trans('countries.Panama') !!}</option>
            <option value="Papua New Guinea">{!! trans('countries.Papua New Guinea') !!}</option>
            <option value="Paraguay">{!! trans('countries.Paraguay') !!}</option>
            <option value="Peru">{!! trans('countries.Peru') !!}</option>
            <option value="Philippines">{!! trans('countries.Philippines') !!}</option>
            <option value="Pitcairn">{!! trans('countries.Pitcairn') !!}</option>
            <option value="Poland">{!! trans('countries.Poland') !!}</option>
            <option value="Portugal">{!! trans('countries.Portugal') !!}</option>
            <option value="Puerto Rico">{!! trans('countries.Puerto Rico') !!}</option>
            <option value="Qatar">{!! trans('countries.Qatar') !!}</option>
            <option value="Reunion">{!! trans('countries.Reunion') !!}</option>
            <option value="Romania">{!! trans('countries.Romania') !!}</option>
            <option value="Russian Federation">{!! trans('countries.Russian Federation') !!}</option>
            <option value="Rwanda">{!! trans('countries.Rwanda') !!}</option>
            <option value="Saint Barthelemy">{!! trans('countries.Saint Barthelemy') !!}</option>
            <option value="Saint Helena">{!! trans('countries.Saint Helena') !!}</option>
            <option value="Saint Kitts and Nevis">{!! trans('countries.Saint Kitts and Nevis') !!}</option>
            <option value="Saint Lucia">{!! trans('countries.Saint Lucia') !!}</option>
            <option value="Saint Martin">{!! trans('countries.Saint Martin') !!}</option>
            <option value="Saint Pierre and Miquelon">{!! trans('countries.Saint Pierre and Miquelon') !!}</option>
            <option value="Saint Vincent and the Grenadines">{!! trans('countries.Saint Vincent and the Grenadines') !!}</option>
            <option value="Samoa">{!! trans('countries.Samoa') !!}</option>
            <option value="San Marino">{!! trans('countries.San Marino') !!}</option>
            <option value="Sao Tome and Principe">{!! trans('countries.Sao Tome and Principe') !!}</option>
            <option value="Saudi Arabia">{!! trans('countries.Saudi Arabia') !!}</option>
            <option value="Senegal">{!! trans('countries.Senegal') !!}</option>
            <option value="Serbia">{!! trans('countries.Serbia') !!}</option>
            <option value="Serbia and Montenegro">{!! trans('countries.Serbia and Montenegro') !!}</option>
            <option value="Seychelles">{!! trans('countries.Seychelles') !!}</option>
            <option value="Sierra Leone">{!! trans('countries.Sierra Leone') !!}</option>
            <option value="Singapore">{!! trans('countries.Singapore') !!}</option>
            <option value="St Martin">{!! trans('countries.St Martin') !!}</option>
            <option value="Slovakia">{!! trans('countries.Slovakia') !!}</option>
            <option value="Slovenia">{!! trans('countries.Slovenia') !!}</option>
            <option value="Solomon Islands">{!! trans('countries.Solomon Islands') !!}</option>
            <option value="Somalia">{!! trans('countries.Somalia') !!}</option>
            <option value="South Africa">{!! trans('countries.South Africa') !!}</option>
            <option value="South Georgia and the South Sandwich Islands">{!! trans('countries.South Georgia and the South Sandwich Islands') !!}</option>
            <option value="South Sudan">{!! trans('countries.South Sudan') !!}</option>
            <option value="Spain">{!! trans('countries.Spain') !!}</option>
            <option value="Sri Lanka">{!! trans('countries.Sri Lanka') !!}</option>
            <option value="Sudan">{!! trans('countries.Sudan') !!}</option>
            <option value="Suriname">{!! trans('countries.Suriname') !!}</option>
            <option value="Svalbard and Jan Mayen">{!! trans('countries.Svalbard and Jan Mayen') !!}</option>
            <option value="Swaziland">{!! trans('countries.Swaziland') !!}</option>
            <option value="Sweden">{!! trans('countries.Sweden') !!}</option>
            <option value="Switzerland">{!! trans('countries.Switzerland') !!}</option>
            <option value="Syrian Arab Republic">{!! trans('countries.Syrian Arab Republic') !!}</option>
            <option value="Taiwan, Province of China">{!! trans('countries.Taiwan, Province of China') !!}</option>
            <option value="Tajikistan">{!! trans('countries.Tajikistan') !!}</option>
            <option value="Tanzania, United Republic of">{!! trans('countries.Tanzania, United Republic of') !!}</option>
            <option value="Thailand">{!! trans('countries.Thailand') !!}</option>
            <option value="Timor-Leste">{!! trans('countries.Timor-Leste') !!}</option>
            <option value="Togo">{!! trans('countries.Togo') !!}</option>
            <option value="Tokelau">{!! trans('countries.Tokelau') !!}</option>
            <option value="Tonga">{!! trans('countries.Tonga') !!}</option>
            <option value="Trinidad and Tobago">{!! trans('countries.Trinidad and Tobago') !!}</option>
            <option value="Tunisia">{!! trans('countries.Tunisia') !!}</option>
            <option value="Turkey">{!! trans('countries.Turkey') !!}</option>
            <option value="Turkmenistan">{!! trans('countries.Turkmenistan') !!}</option>
            <option value="Turks and Caicos Islands">{!! trans('countries.Turks and Caicos Islands') !!}</option>
            <option value="Tuvalu">{!! trans('countries.Tuvalu') !!}</option>
            <option value="Uganda">{!! trans('countries.Uganda') !!}</option>
            <option value="Ukraine">{!! trans('countries.Ukraine') !!}</option>
            <option value="United Arab Emirates">{!! trans('countries.United Arab Emirates') !!}</option>
            <option value="United Kingdom">{!! trans('countries.United Kingdom') !!}</option>
            <option value="United States">{!! trans('countries.United States') !!}</option>
            <option value="United States Minor Outlying Islands">{!! trans('countries.United States Minor Outlying Islands') !!}</option>
            <option value="Uruguay">{!! trans('countries.Uruguay') !!}</option>
            <option value="Uzbekistan">{!! trans('countries.Uzbekistan') !!}</option>
            <option value="Vanuatu">{!! trans('countries.Vanuatu') !!}</option>
            <option value="Venezuela">{!! trans('countries.Venezuela') !!}</option>
            <option value="Viet Nam">{!! trans('countries.Viet Nam') !!}</option>
            <option value="Virgin Islands, British">{!! trans('countries.Virgin Islands, British') !!}</option>
            <option value="Virgin Islands, U.s.">{!! trans('countries.Virgin Islands, U.s.') !!}</option>
            <option value="Wallis and Futuna">{!! trans('countries.Wallis and Futuna') !!}</option>
            <option value="Western Sahara">{!! trans('countries.Western Sahara') !!}</option>
            <option value="Yemen">{!! trans('countries.Yemen') !!}</option>
            <option value="Zambia">{!! trans('countries.Zambia') !!}</option>
            <option value="Zimbabwe">{!! trans('countries.Zimbabwe') !!}</option>
        </select>

        <span class="form-text text-danger"
              id="country_error"></span>
    </div>
<!--end::Group-->
